#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/dist/bin/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/dist/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/dist/bin/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/dist/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules/next/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/next@14.0.3_@babel+core@7.2_c176deb768d5ad4f586932c5c8d2898e/node_modules:/mnt/c/Users/Admin/Documents/Веркин/music-room/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../next/dist/bin/next" "$@"
else
  exec node  "$basedir/../next/dist/bin/next" "$@"
fi
