import { 
  Music, 
  Users, 
  User, 
  LogOut, 
  Moon, 
  Sun, 
  Monitor, 
  Menu, 
  X, 
  Search,
  Share,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  List,
  MessageCircle,
  MoreHorizontal
} from 'lucide-react'

export const Icons = {
  music: Music,
  users: Users,
  user: User,
  logout: LogOut,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  menu: Menu,
  close: X,
  search: Search,
  share: Share,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  list: List,
  messageCircle: MessageCircle,
  moreHorizontal: MoreHorizontal
}